import { generateSyncCode, isValidSyncCode } from '../generate-sync-code';

describe('generateSyncCode', () => {
    it('generates a code with AZ- prefix', () => {
        const code = generateSyncCode();
        expect(code).toMatch(/^AZ-/);
    });

    it('generates a 9-character code (AZ- + 6 chars)', () => {
        const code = generateSyncCode();
        expect(code).toHaveLength(9);
    });

    it('uses only unambiguous characters', () => {
        // Run multiple times to increase confidence
        for (let i = 0; i < 100; i++) {
            const code = generateSyncCode();
            const body = code.slice(3); // Remove "AZ-"
            // Should NOT contain 0, O, 1, I, L
            expect(body).not.toMatch(/[01ILO]/);
        }
    });

    it('generates unique codes', () => {
        const codes = new Set<string>();
        for (let i = 0; i < 100; i++) {
            codes.add(generateSyncCode());
        }
        // All 100 should be unique
        expect(codes.size).toBe(100);
    });
});

describe('isValidSyncCode', () => {
    it('validates correct codes', () => {
        expect(isValidSyncCode('AZ-X7K9M2')).toBe(true);
        expect(isValidSyncCode('AZ-ABCDEF')).toBe(true);
        expect(isValidSyncCode('AZ-234567')).toBe(true);
    });

    it('accepts lowercase input', () => {
        expect(isValidSyncCode('az-x7k9m2')).toBe(true);
    });

    it('rejects invalid formats', () => {
        expect(isValidSyncCode('')).toBe(false);
        expect(isValidSyncCode('AZ-')).toBe(false);
        expect(isValidSyncCode('AZ-SHORT')).toBe(false); // 5 chars
        expect(isValidSyncCode('AZ-TOOLONG9')).toBe(false); // 7 chars
        expect(isValidSyncCode('XX-X7K9M2')).toBe(false); // wrong prefix
        expect(isValidSyncCode('X7K9M2')).toBe(false); // no prefix
    });

    it('rejects ambiguous characters (0, O, 1, I, L)', () => {
        expect(isValidSyncCode('AZ-0BCDEF')).toBe(false); // 0
        expect(isValidSyncCode('AZ-OBCDEF')).toBe(false); // O
        expect(isValidSyncCode('AZ-1BCDEF')).toBe(false); // 1
        expect(isValidSyncCode('AZ-IBCDEF')).toBe(false); // I
        expect(isValidSyncCode('AZ-LBCDEF')).toBe(false); // L
    });

    it('validates all codes generated by generateSyncCode', () => {
        for (let i = 0; i < 50; i++) {
            const code = generateSyncCode();
            expect(isValidSyncCode(code)).toBe(true);
        }
    });
});
